# Generated by Django 5.0.2 on 2024-04-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('profesion', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('imagen_sujeto', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'informacion',
                'verbose_name_plural': 'informaciones',
            },
        ),
    ]
